-- Adicionar novas colunas para indicadores em annual_fundamentals
ALTER TABLE public.annual_fundamentals 
ADD COLUMN IF NOT EXISTS roe NUMERIC,
ADD COLUMN IF NOT EXISTS roa NUMERIC,
ADD COLUMN IF NOT EXISTS roic NUMERIC,
ADD COLUMN IF NOT EXISTS dividend_yield NUMERIC,
ADD COLUMN IF NOT EXISTS p_l NUMERIC,
ADD COLUMN IF NOT EXISTS p_vp NUMERIC,
ADD COLUMN IF NOT EXISTS ev_ebitda NUMERIC,
ADD COLUMN IF NOT EXISTS div_liquida_ebitda NUMERIC,
ADD COLUMN IF NOT EXISTS liq_corrente NUMERIC,
ADD COLUMN IF NOT EXISTS current_price NUMERIC,
ADD COLUMN IF NOT EXISTS cagr_receitas_5a NUMERIC,
ADD COLUMN IF NOT EXISTS cagr_lucros_5a NUMERIC;